# Héctor Heredia
# José García
# Iván Sandoval

Leyendo el dataset `examen2.csv` responda las siguientes preguntas: 
Revise todos los tipos de dato y responda:

1. ¿Cuáles columnas NO corresponden con el tipo de dato que se leyó en el CSV? Señale qué tipo de dato le corresponde.

2. Transforme las columnas del punto anterior en el tipo de dato que corresponda. Reactivos:
    a. Transformación de las columnas.
    b. Responda:
        i. ¿Cuántos nulos hay por columna después de haber transformado los tipos de datos?

3. Estandarice textos. Reactivos:
    a. ¿Qué columna necesita estandarizar textos? En caso de no existir, responda "no existen columnas".  En caso de existir, señale los b. textos que se necesitan estandarizar. 
    c. ¿Cuál es el segundo valor que más se repite y con cuantos datos? 

4. Extraiga datos. Reactivos:
    a. ¿Qué es lo que tiene que extraer de la columna `cantidad_de_empleados`?
    b. ¿Cómo define una expresión regular para extraer la cantidad de trabajadores?
    c. Extraiga la cantidad de trabajadores.
    d. ¿Cuántos trabajadores hay en total? 
    
5. Describa sus datos:
    a. ¿Cuál es la proporción nulos hay en `cantidad_de_camaras`? Si no hay nulos ponga "0%".
    b. ¿Cuál es la media de `cantidad_de_camaras`? 
    c. ¿Cuál es el municipio menos inseguro? Analice bien su respuesta. 
    d. ¿Qué categoría de la variable `banco_inseguro` tiene menos trabajadores en promedio?
    e. Suponiendo que utilizará un modelo que utiliza coeficientes multiplicando a sus variables y este dataset, ¿necesita estandarizar?

In [470]:
import os
import re
import datetime
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import pandas as pd
from copy import deepcopy
import numpy as np
%matplotlib inline
plt.style.use('ggplot')

In [471]:
basedir = '.'
df = pd.read_csv(os.path.join(basedir, 'examen2.csv'))

In [472]:
df.head()

,ubicado_en_avenida,empresa_recolectora_de_dinero,abierto_en_fines_de_semana,dias_para_recoleccion_de_dinero,municipio,cantidad_de_camaras,banco_inseguro,cantidad_de_empleados
0,Falso,Touché-Coulé,NaN,7.0,zapopan,N.A.,0,hay 6.5 trabajadores para los dias habiles
1,NaN,Touché-Coulé,NaN,21.0,Guadalajara,N.A.,1,8 Trabajadores
2,Falso,Touché-Coulé,NaN,18.0,zapopan,N.A.,0,hay 10 trabajadores para los dias habiles
3,True,Touché-Coulé,False,12.0,zapopan,6.0,0,tenemos 8.5 trabajadores para los 7 dias de la...
4,NaN,Touché-Coulé,NaN,15.0,zapopan,N.A.,0,contamos con 159.5 trabajadores para los 5 dia...

In [473]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15147 entries, 0 to 15146
Data columns (total 8 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   ubicado_en_avenida               12519 non-null  object
 1   empresa_recolectora_de_dinero    15147 non-null  object
 2   abierto_en_fines_de_semana       4696 non-null   object
 3   dias_para_recoleccion_de_dinero  15147 non-null  float64
 4   municipio                        15147 non-null  object
 5   cantidad_de_camaras              15147 non-null  object
 6   banco_inseguro                   15147 non-null  int64
 7   cantidad_de_empleados            15147 non-null  object
dtypes: float64(1), int64(1), object(6)
memory usage: 946.8+ KB

1. ¿Cuáles columnas NO corresponden con el tipo de dato que se leyó en el CSV? Señale qué tipo de dato le corresponde.

In [474]:
'''
0   empresa_recolectora_de_dinero    15147 non-null  object     ->  bool
1   abierto_en_fines_de_semana       4696 non-null   object     ->  string
2   dias_para_recoleccion_de_dinero  15147 non-null  float64    ->  bool
3   municipio                        15147 non-null  object     ->  int
4   cantidad_de_camaras              15147 non-null  object     ->  int
5   banco_inseguro                   15147 non-null  int64      ->  bool
6   cantidad_de_empleados            15147 non-null  object     ->  string
'''

ueA = "ubicado_en_avenida"
eRD = "empresa_recolectora_de_dinero"
aWE = "abierto_en_fines_de_semana"
dRD = "dias_para_recoleccion_de_dinero"
mun = "municipio"
cdC = "cantidad_de_camaras"
bIn = "banco_inseguro"
cdE = "cantidad_de_empleados"

2. Transforme las columnas del punto anterior en el tipo de dato que corresponda. Reactivos:

    a. Transformación de las columnas.

    b. Responda:


        i. ¿Cuántos nulos hay por columna después de haber transformado los tipos de datos?

In [475]:
df[ueA].unique()

array(['Falso', nan, 'True'], dtype=object)

In [476]:
df[aWE].unique()

array([nan, False, True], dtype=object)

In [477]:
# boolean
df[ueA] = df[ueA].replace(np.nan, pd.NA)
df[ueA] = df[ueA].replace("Falso", False)
df[ueA] = df[ueA].replace("True", True)

df[aWE] = df[aWE].replace(np.nan, pd.NA)
df[aWE] = df[aWE].replace("Falso", False)
df[aWE] = df[aWE].replace("True", True)

df[bIn] = df[bIn].replace(np.nan, pd.NA)
df[bIn] = df[bIn].replace("Falso", False)
df[bIn] = df[bIn].replace("True", True)


# numércos
df[cdC] = pd.to_numeric(df[cdC], errors="coerce")

# regex con "trabajadores" para cantidad de trabajadores
# ? Ver inciso 4 pls

# contamos la cantidad de nulos
df.isnull().sum()

ubicado_en_avenida                  2628
empresa_recolectora_de_dinero          0
abierto_en_fines_de_semana         10451
dias_para_recoleccion_de_dinero        0
municipio                              0
cantidad_de_camaras                10603
banco_inseguro                         0
cantidad_de_empleados                  0
dtype: int64

3. Estandarice textos. Reactivos:


    a. ¿Qué columna necesita estandarizar textos? En caso de no existir, responda "no existen columnas".  En caso de existir, señale los 
    
    b. textos que se necesitan estandarizar. 

    c. ¿Cuál es el segundo valor que más se repite y con cuantos datos?

In [478]:
# capitalizamos el municipio
df[mun] = df[mun].str.strip().str.capitalize()

# revisamos
df[mun].value_counts()

municipio
Guadalajara    10395
Zapopan         4715
Tlajomulco        37
Name: count, dtype: int64

In [479]:
# obtener el segundo valor más común en municipio
mun2ndMode = df[mun].value_counts().iloc[1]
mun2ndModeName = df[mun].value_counts().index[1]
print(f"Segundo valor más repetido: {mun2ndModeName} con {mun2ndMode} datos")

Segundo valor más repetido: Zapopan con 4715 datos

4. Extraiga datos. Reactivos:

    a. ¿Qué es lo que tiene que extraer de la columna `cantidad_de_empleados`?

    b. ¿Cómo define una expresión regular para extraer la cantidad de trabajadores?

    c. Extraiga la cantidad de trabajadores.
    
    d. ¿Cuántos trabajadores hay en total?

In [480]:
# En la parte de acá reemplazamos la columna porque no se pierde info (creo)
df[cdE] = df[cdE].str.lower()
df[cdE] = df[cdE].apply(
    lambda x: re.findall(r'(\d+\.?\d*)\s*trabajadores', x) if isinstance(x, str) else []
)
df[cdE] = df[cdE].apply(lambda x: x[0] if x else None)

# total de trabajadores post extracción
totalTrabajadores = df[cdE].astype(float).sum()
print(f"Total de trabajadores: {totalTrabajadores}")

Total de trabajadores: 191570.0

5. Describa sus datos:

    a. ¿Cuál es la proporción nulos hay en `cantidad_de_camaras`? Si no hay nulos ponga "0%".

    b. ¿Cuál es la media de `cantidad_de_camaras`? 

    c. ¿Cuál es el municipio menos inseguro? Analice bien su respuesta. 

    d. ¿Qué categoría de la variable `banco_inseguro` tiene menos trabajadores en promedio?

    e. Suponiendo que utilizará un modelo que utiliza coeficientes multiplicando a sus variables y este dataset, ¿necesita estandarizar?
    |

In [481]:
df[mun].unique()

array(['Zapopan', 'Guadalajara', 'Tlajomulco'], dtype=object)

In [482]:
# a) proporción de nulos de las camaras
propCamaras = df[cdC].isnull().mean() * 100
print(f"Proporción de nulos en cantidad_de_camaras: {propCamaras:.2f}%")

Proporción de nulos en cantidad_de_camaras: 70.00%

In [483]:
# b) media de cámaras sin nulos
meanCamaras = df[cdC].mean()
print(f"Media de cantidad_de_camaras: {meanCamaras:.2f}")

Media de cantidad_de_camaras: 5.62

c) determinando el municipio más inseguro
En este inciso realmente sería una tontería analizar la inseguridad con este tipo de datos. La notación booleana para UNA CATEGORÍA de banco inseguro con un 0 y un 1 es demasiado genérica para tomar decisiones o un análisis prudente. De esta manera
hace falta mucho contexto respecto a un municipio como para afirmar si es inseguro o no y el por qué.

In [484]:
# d) calcular el promedio de trabajadores según cats de banco inseguro
df[cdE] = pd.to_numeric(df[cdE], errors='coerce')
meanWorkers = df.groupby(bIn)[cdE].mean()
catLWorkers = meanWorkers.idxmin()
print(f"Cat con menos trabajadores en promedio: Banco inseguro: {catLWorkers}")

Cat con menos trabajadores en promedio: Banco inseguro: 0

In [485]:
# e)
# Sí es necesario estandarizar los datos para un modelo basado en coeficientes
# Tengo entendido que se debe estandarizar si las escalas de las variables son muy diferentes
# Así que en este caso no creo que haga mucha falta por los datos siguientes
df.describe()

,dias_para_recoleccion_de_dinero,cantidad_de_camaras,banco_inseguro,cantidad_de_empleados
count,15147.000000,4544.000000,15147.000000,15147.000000
mean,15.872318,5.623019,0.499373,12.647389
std,3.907918,1.519789,0.500016,21.049490
min,3.000000,0.000000,0.000000,3.000000
25%,13.000000,5.000000,0.000000,8.000000
50%,15.000000,6.000000,0.000000,9.500000
75%,18.000000,7.000000,1.000000,11.000000
max,30.000000,11.000000,1.000000,159.500000